- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - homedirectory
  vars:
    homebrew_repositories:
 
    homebrew_packages:
      - ansible
      - python
      - git
      - go
      - htop-osx
      - openssl
      - sl
      - terraform
      - tmux
      - tree
      - wget
      - zsh
      - grep
      
 
    homebrew_cask_repositories:
 
    homebrew_cask_packages:
      - firefox
      - google-chrome
      - google-japanese-ime
      - karabiner
      - slack
      - vagrant
      - virtualbox
      - docker
      - atom
      - evernote
      - CalendarFree
      - bitbar
      - Clipy
      - iTerm
      - LINE
      - Messenger
      - Skitch
      - InsomniaX
      - Alfred 2
      - Near Lock
      - Twitter
      - Memory Clean


