- hosts: localhost
  connection: local
  roles:
    - homebrew
    - homebrew-cask
    - homedirectory
  vars:
    homebrew_repositories:
 
    homebrew_packages:
      - ansible
      - python
      - git
      - go
      - htop-osx
      - openssl
      - sl
      - terraform
      - tmux
      - tree
      - wget
      - zsh
      - reattach-to-user-namespace
      
 
    homebrew_cask_repositories:
 
    homebrew_cask_packages:
      - firefox
      - google-chrome
      - google-japanese-ime
      - bitbar
      - karabiner
      - karabiner-elements
      - slack
      - chatwork
      - evernote
      - iterm2
      - virtualbox
      - skitch
      - alfred
      - near-lock
      - 1password
