- name: Update homebrew itself first
  homebrew: update_homebrew=yes

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item }}
  with_items:
    - firefox
    - google-chrome
    - google-japanese-ime
    - bitbar
    - karabiner
    - karabiner-elements
    - slack
    - chatwork
    - evernote
    - iterm2
    - virtualbox
    - skitch
    - alfred
    - near-lock
    - 1password
