- name: Install Homebrew cask packages
  tags: homebrew-cask
  homebrew_cask: name={{ item }}
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  ignore_errors: yes
  loop:
    - "{{ CASK_TARGETS }}"
