- name: Copy home directory .cache/dein
  file: path={{ item.name }} 
        state=directory 
        mode=0755
  with_items:
  - { name: '~/.cache/dein' }

- name: Copy home directory Files.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: roles/homedirectory/files/.config, dest: ~/ }
  - { src: roles/homedirectory/files/.bash_profile, dest: ~/ }
  - { src: roles/homedirectory/files/.gitconfig, dest: ~/ }
  - { src: roles/homedirectory/files/.commit_template, dest: ~/ }
  - { src: roles/homedirectory/files/.tmux.conf, dest: ~/ }
  - { src: roles/homedirectory/files/.vimrc, dest: ~/ }
  - { src: roles/homedirectory/files/.zshrc, dest: ~/ }
  - { src: roles/homedirectory/files/.gvimrc, dest: ~/ }
  - { src: roles/homedirectory/files/.vim, dest: ~/ }

- name: Download dein.vim install.sh
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: ~/.config/nvim
    mode: 0755
 
- name: install.sh dein.vim
  shell: sh ~/.config/nvim/installer.sh ~/.cache/dein
