- name: Copy home directory Files.
  tags: homedirectory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - "{{ HOMEDIR_TARGETS }}"

- name: git_clone iterm2 color schema Japanesque
  git:
    repo: "https://github.com/aereal/dotfiles.git"
    dest: "~/Desktop/dotfiles/"
  ignore_errors: yes

- name: git_clone iterm2 fonts
  git:
    repo: "https://github.com/powerline/fonts.git"
    dest: "~/Desktop/fonts/"
  ignore_errors: yes

- name: install.sh fonts
  shell: |
    sh ~/Desktop/fonts/install.sh
    rm -rf ~/Desktop/fonts
  ignore_errors: yes

- name: install git-prompt
  shell: |
    mkdir ~/.zsh
    cd ~/.zsh
    curl -o git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    curl -o git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    curl -o _git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
  ignore_errors: yes

- name: Download Session Manager Plugin
  get_url:
    url: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip
    dest: /tmp/sessionmanager-bundle.zip
    mode: '0644'

- name: Unzip Session Manager Plugin
  unarchive:
    src: /tmp/sessionmanager-bundle.zip
    dest: /tmp/
    remote_src: yes

- name: Install Session Manager Plugin
  command: >
    ./install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
  args:
    chdir: /tmp/sessionmanager-bundle/
  ignore_errors: yes

- name: Remove downloaded files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/sessionmanager-bundle.zip
    - /tmp/sessionmanager-bundle/
