- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  ignore_errors: yes
  with_items:
    - "{{ BREW_TARGETS }}"

- name: Install pip packages
  pip: name={{ item }}
  with_items:
      - powerline-status
