- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  ignore_errors: yes
  loop:
    - "{{ BREW_TARGETS }}"

- name: Install pip packages
  pip: name={{ item }}
  loop:
      - powerline-status
