- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install homebrew tap packages
  homebrew_tap: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREWTAP_TARGETS }}" 

- name: Install homebrew packages
  homebrew: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREW_TARGETS }}"

- name: Install python 3.8.2  
  tags: homebrew
  ignore_errors: yes
  shell: pyenv install 3.8.2 && pyenv global 3.8.2

- name: Install pip 
  tags: homebrew
  shell: easy_install pip

- name: upgrade pip 
  tags: homebrew
  shell: pip install --upgrade pip

- name: Install pip packages
  pip: name={{ item }}
  tags: homebrew
  loop:
    - "{{ PIP_TARGETS }}"

