- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install brew tap packages
  homebrew_tap: name={{ item }}
  ignore_errors: yes
  loop:
    - "{{ BREWTAP_TARGETS }}" 

- name: Install homebrew packages
  homebrew: name={{ item }}
  ignore_errors: yes
  loop:
    - "{{ BREW_TARGETS }}"

- name: Install pip packages
  pip: name={{ item }}
  loop:
    - "{{ PIP_TARGETS }}"
