- name: Update homebrew itself first
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items:
      - ansible
      - python
      - git
      - go
      - htop-osx
      - openssl
      - sl
      - terraform
      - tmux
      - tree
      - wget
      - zsh
      - reattach-to-user-namespace
