- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  ignore_errors: yes
  with_items:
      - ansible
      - python
      - git
      - go
      - htop
      - openssl
      - sl
      - terraform
      - tmux
      - tree
      - wget
      - zsh
      - reattach-to-user-namespace
      - awscli
      - cask
      - docker
      - docker-compose
      - grep
      - putty
      - telnet
      - tree
      - watch
      - w3m
      - neovim
      - iproute2mac
      - watch
      - jq
      - peco
      - ghq
      - gnu-sed

- name: Install pip packages
  pip: name={{ item }}
  with_items:
      - powerline-status
