- name: Update homebrew
  tags: homebrew
  homebrew: update_homebrew=yes

- name: Install homebrew tap packages
  homebrew_tap: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREWTAP_TARGETS }}"

- name: Install homebrew packages
  homebrew: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREW_TARGETS }}"

#manual
- name: Install python 3.12.0
  tags: homebrew
  ignore_errors: yes
  shell: |
    pyenv install 3.12.0
    pyenv global 3.12.0

- name: upgrade pip, install powerline-status
  tags: homebrew
  ignore_errors: yes
  shell: |
    pip install --upgrade pip
    pip install powerline-status
